MonishRaman/Placify-Smarter_Placements-Sharper_Talent

src/components/Footer.jsx, src/components/ThemeToggle.jsx, src/context/ThemeContext.jsx, src/main.jsx, src/pages/AuthPage.jsx, src/pages/Dashboard.jsx, src/pages/InterviewInterface.jsx, src/pages/LandingPage.jsx, src/pages/ResultsPage.jsx, tailwind.config.js
issue #4 
* **Created a `ThemeContext`** inside `components/context/ThemeContext.jsx`
→ Manages `dark` / `light` theme state globally using React Context API
→ Persists user’s theme preference in `localStorage`
*  **Added a Dark Mode Toggle Button**
→ Placed in the **Navbar** for easy access
→ Instantly switches theme across the app
*  **Updated `tailwind.config.js`**
→ Enabled `darkMode: "class"` for class-based dark theme handling
→ Ensured Tailwind classes support dark variants
*  **Applied conditional classNames** to key components/pages
→ Used `dark:` prefix to style elements responsively
→ Pages like `index.js`, `Navbar.jsx`, and layout containers updated to reflect theme dynamically
*  **Tested across multiple pages and edge cases**
→ Theme persists on refresh
→ Works cleanly with …
=> feat/ Implement Dark Mode Functionality #4

server/models/User.js, server/package-lock.json, server/package.json, server/routes/health.js, server/server.js
issue #7
This PR adds the foundational backend setup to the project by creating an Express.js server connected to MongoDB. It includes a basic health check route and defines the initial User model using Mongoose.
---
* 📁 Created a new `server/` directory to house all backend logic.
* 🔄 Initialized a Node.js project using `npm init`.
* 📦 Installed the following essential packages:
* `express` for server framework
* `cors` for handling CORS requests
* `dotenv` for environment variables
* `mongoose` for MongoDB ORM
* 🌐 Setup `server.js` to:
* Start an Express server
* Load environment variables via `.env`
* Connect to MongoDB
* Enable JSON parsing and CORS middleware
* Add a **health check route** at `GET /api/health`
* 🧠 Defined the `User` model with `email` and `password` fields in …
=> Set up initial nodejs server and user model

package-lock.json, package.json, src/App.jsx, src/pages/AuthPage.jsx, src/pages/Dashboard.jsx, src/pages/InterviewInterface.jsx, src/pages/LandingPage.jsx, src/pages/ResultsPage.jsx
Reverts MonishRaman/Placify-Smarter_Placements-Sharper_Talent#22
once when i pushed this the website is looking blank once please look over that once
=> Revert "Implemented smooth fade like page transitions across app "

README.md
Updated readme.md: A quick, user-friendly, and beginner-friendly guide #24 
-----------
This clean and concise guide aims to help newcomers understand the problem and solution in a straightforward manner. It provides a quick overview of the project, allowing readers to grasp the key concepts effortlessly. The guide is designed to be accessible to beginners, explaining technical terms and processes in simple language.
**By reading this updated readme, you'll gain a clear understanding of:**
1. The problem the project addresses
2. The proposed solution and its implementation
3. How to get started with the project
4. Steps to begin contributing effectively
This streamlined guide ensures that anyone interested in the project can quickly comprehend its purpose and start contributing without …
=> refactor: update README for clarity and consistency #24

src/pages/ResultsPage.jsx
- Redesigned empty state with completion message
- Added 'Dashboard' and 'New Interview' buttons
- Maintained existing results display
=> feat: add exit options to ResultsPage empty state

src/components/ThemeToggle.jsx, src/pages/LandingPage.jsx
This is a fully responsive, modern navbar built with Tailwind CSS and lucide-react icons. It adapts gracefully to both mobile and desktop screens with a minimal and consistent UI experience.
Closes #45
=> Enhanced the UI of navbar

src/pages/ResultsPage.jsx
🔧 Pull Request: Make ResultsPage Graph Rendering Dynamic
📝 Description
This PR addresses the issue where graphs on the ResultsPage.jsx were dependent on hardcoded/static user IDs. As a result, the graph section would render properly for new users.
✅ What’s Implemented:
Dynamic data fetching based on current user ID.
Introduced fallback logic with mock data for new users.
Conditional rendering for:
Loading state
Missing/undefined data
Ensured all graph components render regardless of user ID availability.
Improved component resilience and user experience.
❌Demo image (my mistake; chart label was not visible properly)
✅fixed demo image
🔍 Linked Issue
Closes #46 
🧪 Tested Scenarios:
✅ Graphs render with valid user data.
✅ Graphs display fallback/mock data for unknown user IDs.
✅ Graph …
=> added resultpage-garph

src/components/Footer.jsx
This is the updated footer 
closes #49
=> Enhance Footer component with improved layout, added back-to-top button, and updated social links

package-lock.json, package.json, server/middleware/authMiddleware.js, server/models/User.js, server/package-lock.json, server/package.json, server/routes/auth.js, server/routes/health.js, server/server.js, src/pages/AuthPage.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
This PR implements the **entire authentication system** as outlined in Issue #8, along with additional requirements specified during review.
All core backend APIs, frontend form integrations, and JWT-based authentication are fully functional and tested.
closes #8 
---
* `models/User.js` → Updated schema to include `role` field and dynamic fields (Student, Institution, Employee, Company).
* `routes/auth.js` → New authentication routes:
* `POST /api/auth/register` → User registration with role validation and password hashing (bcrypt).
* `POST /api/auth/login` → User login with JWT token generation.
* `middleware/authMiddleware.js` → JWT token verification middleware.
* `bcryptjs` → For password hashing.
* `jsonwebtoken` → For generating and validating JWT tokens.
* All users (students, …
=> Implement complete role based user authentication flow

package-lock.json, package.json, src/App.jsx, src/pages/AuthPage.jsx, src/pages/Dashboard.jsx, src/pages/InterviewInterface.jsx, src/pages/LandingPage.jsx, src/pages/RoleSelectionPage.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
Description:
This PR introduces smooth fade-in/out transitions across major pages using framer-motion, significantly improving the user experience by making navigation feel more fluid and polished.
📦 Changes Made:
Installed framer-motion for animation handling
Wrapped app routes in <AnimatePresence mode="wait"> inside _app.jsx
Added motion.div wrappers with initial, animate, and exit props to the following pages:
`AuthPage.jsx`
`Dashboard.jsx`
`InterviewInterface.jsx`
`LandingPage.jsx`
`RolesSelectionPage.jsx`
`register/StudentForm.jsx`
`register/IndustryForm.jsx`
`register/CompanyForm.jsx`
`register/EmployeeForm.jsx`
Each page now includes a quick fade and onScroll smooth animation and transitions on mount/unmount for smooth transitions.
closes #5
=> Added smooth transition on pages

src/components/InstitutionDashboard.jsx
This PR adds role-based redirection logic after successful login.
Based on the role (student, employee, institution, company), users are redirected to their respective dashboards.
I had implemented this earlier and pushed the code but forgot to raise the PR. So, I made a small change to trigger the PR now.
=> implemented role-based JWT login and dashboard redirection

src/components/ThemeToggle.jsx, src/pages/LandingPage.jsx
Summary:
Redesigned the landing page navbar with modern glassmorphism effects, improved alignment, and a dynamic scroll-based appearance system.
Key Features:
Dynamic Color Transition: Navbar seamlessly blends with hero section initially, then transitions to white background when scrolling past hero
Enhanced Blur Effects: Improved backdrop-blur implementation with proper cross-browser support ([WebkitBackdropFilter]
Better Visual Hierarchy: Improved button styling, spacing, and typography for better user experience
Modernized Theme Toggle: Replaced emoji icons with professional Lucide icons (Sun/Moon) and added smooth rotation animations
Responsive Design: Enhanced mobile menu with consistent blur effects and smooth animations
Smooth Transitions: All state changes now have proper 500ms …
=> feat:  Enhanced Navbar with Dynamic Scroll Effects and Improved Theme Toggle

src/pages/LandingPage.jsx
Summary
Complete redesign of the landing page hero section to accurately showcase Placify as an AI-powered recruitment and skill-assessment platform that streamlines 60-70% of campus placements.
Key Updates
Content Alignment
Updated messaging to reflect recruitment automation platform
Emphasized 60-70% process automation capability
Added industry-specific statistics and metrics
Refined call-to-action to "Transform Your Placements"
Visual Enhancements
Modern two-column responsive layout
Interactive AI dashboard visualization
Animated skill assessment progress bars
Floating AI particles and rotation effects
Enhanced button designs with gradient overlays
User Experience
Smooth scroll animations and transitions
Mobile-optimized responsive design
Dark mode compatibility maintained
Clear …
=> Redesigned Hero Section

src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
This PR makes the UI of both signin and signup form consistent.
Closes #72
=> Made the ui of signin and signup form consistent

server/controllers/authController.js, server/middleware/authMiddleware.js, server/models/Company.js, server/models/Employee.js, server/models/Institution.js, server/models/Student.js, server/routes/auth.js, server/routes/interview.js, server/server.js, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
closes #54 
1. **Created separate models for each user role** (`/models/`):
* `Student.js` – handles student-specific fields (`fullName`, `university`, `major`, `email`, `password`)
* `Institution.js` – handles institution fields (`institutionName`, `website`, `contactPerson`, `email`, `password`)
* `Employee.js` – handles employee fields (`fullName`, `currentCompany`, `jobTitle`, `email`, `password`)
* `Company.js` – handles company-specific fields (`companyName`, `industry`, `hrEmail`, `password`)
2. **Refactored Authentication Routes (`/routes/auth.js`)**
* Added **separate registration endpoints**:
* `POST /register/student`
* `POST /register/institution`
* `POST /register/employee`
* `POST /register/company`
* Updated `POST /login` to dynamically detect the user role and return a JWT …
=> Refactor Authentication: Separate Models for Each User Role

src/pages/RoleSelectionPage.jsx
=> Role Selection Page Design Enhancement

EMAIL_SETUP.md, package-lock.json, package.json, server/controllers/feedbackController.js, server/package-lock.json, server/package.json, server/routes/feedback.js, server/server.js, src/App.jsx, src/components/useLenis.jsx, src/pages/AuthPage.jsx, src/pages/FeedbackPage.jsx, src/utils/emailService.js, start-server.bat
**Bug Fixes:**
- Fixed email/password input icons vanishing on focus (removed scaling animation)
**New Features:**
- Added email-based feedback system with star ratings
- Integrated Lenis smooth scrolling
**Technical Implementation:**
- **Backend:** Nodemailer + Express API (`/api/feedback`)
- **Frontend:** React feedback form with animations
- **Email:** Gmail SMTP integration
- **Scroll:** Lenis smooth scroll implementation
**Setup Required:**
Create `.env` file in `server/` folder with:
```env
PORT=5000
EMAIL_USER=your-email@gmail.com
EMAIL_PASS=your-app-password
FEEDBACK_EMAIL=feedback@yourcompany.com
```
**Screenshots**
**Files modified:**
src/pages/AuthPage.jsx - Fixed icon scaling bug
[FeedbackPage.jsx](vscode-file://vscode-app/c:/Users/Yashvanth%20Sankar/AppData/Local/Programs/Micr …
=> fix: Email Icon Bug + Add Feedback System + Lenis Scroll

package-lock.json, package.json, src/pages/AuthPage.jsx, src/pages/Dashboard.jsx, src/pages/ProfilePage.jsx
This PR includes:
- Implemented role-based redirection after login using the role from the JWT token.
- Completed and tested protected route logic to restrict unauthenticated access.
Tested all redirections and access controls. Resolves issue #10 and #32
=> Implement Role-Based Redirection (#32)and Protected Route Logic (#10)

src/pages/LandingPage.jsx
Made the text size uniform across the stats section
Closes #86
=> Fixed the text size of stats section

server/config/env.js, server/package-lock.json, server/server.js
Added centralized env.js file to manage environment variables using dotenv.
Closes #96
=> feat: add centralized env.js file for environment variable exports 

server/config/db.js, server/package-lock.json, server/package.json, server/server.js
Added a `config/db.js` file to handle MongoDB connection using Mongoose. This improves project structure by keeping the connection logic modular and reusable.
- Created `config/db.js` for MongoDB connection setup.
- Included environment variable check for `DB_URI`.
- Added clean error handling and process exit on failure.
- Used `mongoose.connect()` with basic configuration.
- Add a valid `DB_URI` in your environment file.
- Run the server and ensure successful connection logs.
- Comment out the connection line in `server.js` to test optional usage.
Closes #98
=> feat: add MongoDB database connection using Mongoose

server/server.js
- Implemented global error handler middleware
- Added a 404 route for undefined endpoints
- Improves backend robustness and clarity for API consumers
closes #103
=> Added 404 and global error handling

server/config/db.js, server/config/env.js, server/package-lock.json, server/package.json, server/server.js, src/components/CompanyDashboard.jsx, src/components/EmployeeDashboard.jsx, src/components/InstitutionDashboard.jsx
**PR Title:** Added Role-Based Sample Dashboards with Mock Data
* Created **separate dashboards** for each user role:
* **Institution Dashboard**: Profile icon, student count (mock), placement summary, and student performance view placeholder.
* **Employee Dashboard**: Profile icon, performance metrics placeholder, and job history layout.
* **Company Dashboard**: Profile icon, employees list placeholder, and performance overview layout.
* Reused existing Student Dashboard components where possible to maintain UI consistency.
* Ensured responsive design and role-based redirection post-login.
* **Used mock data** for these dashboards since backend APIs were not yet implemented (backend setup had some flaws which we fixed first).
* All routes integrated and tested for smooth …
=> Created Sample dashboards with Mock data and resolved backend flaws

server/vercel.json, src/components/CompanyDashboard.jsx, src/components/EmployeeDashboard.jsx, src/components/InstitutionDashboard.jsx, src/pages/AuthPage.jsx, src/pages/Dashboard.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
* Connected the registration and login flows to the backend API for secure authentication.
* Removed localStorage-only user persistence and switched to backend-driven JWT authentication.
* Implemented logout functionality: clears JWT token and resets user state on logout.
* Verified complete flow locally and ensured it works on deployed environment as well.
* Minor UI adjustments to the profile dropdown for logout redirection.
**Impact:**
* Registration and login are now production-ready and secure.
* Users can log out successfully, clearing their session state.
* Codebase is now aligned with backend authentication for future features like dashboards and badges.
https://github.com/user-attachments/assets/ead3fe11-c5f5-4876-a894-be6766e0aa97
=> Fixed registration flow

src/App.jsx, src/components/EmployeeDashboard.jsx
=> Made the employee dashboard more dynamic and interactive

server/controllers/authController.js, server/controllers/institutionController.js, server/routes/institutionRoutes.js, server/server.js, src/components/InstitutionDashboard.jsx
Description:
Added filterable department-wise placement graph
Displayed placement trends, recent placements, and top recruiters
Improved dashboard layout and data visualization
closes #117 
closes #135
=> Enhancement in Institution Dashboard

src/components/InterviewLeft.jsx, src/components/InterviewRight.jsx, src/pages/InterviewInterface.jsx
This PR refactors the previously monolithic `InterviewInterface` into a modular, maintainable structure and adds camera/mic control functionality.
---
1. **Component Separation**
* **`InterviewLeft`**:
* Handles camera and microphone access via `navigator.mediaDevices.getUserMedia`.
* Includes fully functional **toggle buttons** for enabling/disabling camera and microphone dynamically.
* Displays real-time status messages (`Camera On`, `Camera Off`, `Mic On`, `Mic Off`).
* Starts and manages media recording using `MediaRecorder`.
* Provides a `stopRecording` callback to the parent for final interview submission.
* **`InterviewRight`**:
* Manages question display and user answer collection.
* Uses a simple chat-like interface to display interview questions sequentially and record user …
=> Implemented camera mic toggle button feature

package-lock.json, src/App.jsx, src/components/CompanyDashboard.jsx
=> Made the company dashboard more attractive and dynamic

package-lock.json, server/package-lock.json, server/package.json, src/components/InterviewRight.jsx, src/lib/geminiHelper.js
This PR enhances the **Interview Page chatbot** to dynamically ask interview questions based on user role and previous answers instead of using a static predefined list.
The bot now behaves more like a real interviewer, with role-specific, context-aware questions and scoring logic.
---
1. **Dynamic Question Generation**
* Integrated **Google Gemini API (Free Model: `gemini-1.5-flash`)**.
* Fallback to a predefined static question set when API is unavailable or overloaded.
* Each next question is generated based on:
* User-selected `role`
* Previous answers
* Interview flow context (prompt instructs the model to behave like an experienced interviewer)
2. **Scoring Mechanism**
* Simple scoring logic: **+1 point** for answers containing **≥ 5 words**.
* Score displayed in the UI for …
=> [Feat]: Added feature of dynamic ques generation

src/pages/Dashboard.jsx
- Implemented a fixed, toggleable sidebar on the left.
- Includes icons + labels: Profile, Dashboard, Resume, Jobs, Coding, Aptitude, Interview, etc.
- Supports light/dark themes.
- Sidebar expands/collapses with smooth transitions.
- Dashboard content adjusts accordingly.
Done with #128
=>  Add Static Quick Menu to Student Dashboard

src/components/InstitutionDashboard.jsx
Description
This PR adds a quick menu sidebar to the left side of the student dashboard, based on the provided UI design. The sidebar improves navigation with a fixed, collapsible layout and full support for both light and dark modes.
Features Implemented
Fixed sidebar that remains visible while scrolling.
Navigation menu includes:
Profile 
Dashboard
View Performance
Student Performance
Department Performance
Generate Reports
Settings
Logout
Toggle button to expand or collapse the sidebar:
> shows full menu with icons and labels
< shows compact vertical menu with icons only
Sidebar supports light and dark themes.
Smooth transitions for toggle and icon changes.
Main dashboard content shifts margin based on sidebar state.
Output:
=>  Add Static Quick Menu to Institute  Dashboard

src/App.jsx, src/components/InstitutionDashboard.jsx
Made the dashboard more attractive
closes #94
=> Institution dashboard

src/components/InterviewRight.jsx, src/pages/InterviewInterface.jsx
Description:
Resolved an issue in the Interview Dashboard where the chat window scrolls upward after sending a message, causing users to lose visibility of the chatbot's latest response.
Fixes Implemented:
Added auto-scroll-to-bottom functionality using scrollIntoView() on the last message.
Ensured chat scrolls to the latest message (user or bot) after every update.
Introduced a scroll detection mechanism:
When the user manually scrolls up, a “Scroll to Bottom” button appears.
Clicking the button smoothly scrolls to the most recent message.
Expected Behavior Now:
After sending a message, the chat automatically scrolls to show the most recent response.
Users never lose visibility of ongoing conversation.
If the user scrolls up, the interface offers an option to return to the bottom easily.
=> New feature

OPTIMIZATION_SUMMARY.md, PERFORMANCE_OPTIMIZATION.md, src/components/Chatbot.jsx, src/components/ThemeToggle.jsx, src/index.css, src/pages/LandingPage.jsx
Resolved the Lag issue and enhanced the UI @MonishRaman Please check
=> Lag Issue Resolved

server/controllers/authController.js, server/models/Company.js, server/models/Employee.js, server/models/Institution.js, server/models/Student.js, server/models/User.js, server/routes/auth.js, src/pages/register/CompanyForm.jsx
This PR refactors our backend user management architecture and updates the authentication flow:
* **Implemented Mongoose Discriminators:**
* Created a single `User` base model with shared fields.
* Added separate discriminator models for `Student`, `Company`, `Institution`, and `Employee`.
* Eliminated redundant schemas and collections for each user type.
* **Refactored Registration Controllers:**
* Updated `registerStudent`, `registerCompany`, `registerInstitution`, and `registerEmployee` to use the new discriminator models.
* Removed redundant `role` handling (handled automatically by Mongoose discriminators).
* **Simplified Login Logic:**
* Now performs a single query on the unified `User` collection instead of checking multiple collections.
* Maintains token-based authentication with …
=> Implemented unified user model (mongoose discriminator)

src/pages/AuthPage.jsx, src/pages/LandingPage.jsx, src/pages/RoleSelectionPage.jsx
This PR updates the brain logo section to add click functionality. When the logo is clicked:
--The user is navigated to the home page (/) using useNavigate from react-router-dom.
--The window smoothly scrolls to the top of the page for better UX.
--A cursor-pointer class is also added to indicate interactivity.
--Added onClick handler to the motion.div wrapping the logo.
--Used navigate('/') and window.scrollTo for routing and scroll.
--Ensured consistent styling and smooth UX.
@MonishRaman Kindly review and approve this PR. Let me know if any changes are needed.
=> Added home page navigation functionality on logo click

src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
=> Fixed missing registration flow

src/App.jsx
> This PR fixes an issue where navigating to unknown routes did not redirect the user properly. Now, all undefined paths are routed to the dashboard, ensuring smoother navigation and error handling.
---
closes #162 
---
Please delete options that are not relevant:
---
Before submitting your PR, check all the points below:
---
> ✅ PRs that follow the structure and guidelines are reviewed and merged faster!
=> Route unknown paths to dashboard

src/App.jsx, src/pages/Student/Jobs.jsx
=> Added static jobs to the job section

src/App.jsx, src/layouts/DashboardLayout.jsx, src/pages/Student/InterviewExperience.jsx
=> Added content to interview experience page

src/pages/LandingPage.jsx
Resolves: #185 
Summary
This pull request addresses a performance issue related to UI lag and jank during hover animations on the landing page and other interactive components. By refactoring animations from JavaScript (Framer Motion whileHover) to more performant CSS transitions, this PR ensures a smoother, 60fps user experience.
Problem
The UI suffered from noticeable lag, particularly on buttons and feature cards, due to heavy Framer Motion animations running on the main thread. This created a jarring user experience and made the application feel less responsive.
Solution
This PR implements the following optimizations as outlined in the PERFORMANCE_OPTIMIZATION.md guide:
Refactored Animations to CSS:
Replaced Framer Motion's whileHover props in src/pages/LandingPage.jsx with new, …
=> Optimize-UI-animation

src/pages/Student/Settings.jsx
=> Added content to the settings page

package-lock.json, package.json, src/pages/Institution/GenerateReports.jsx, src/pages/Institution/Reports.jsx, src/pages/Institution/data/mockData.js, src/pages/Institution/utils/generateReport.js
This PR introduces a complete enhancement to the **Placement Report Generation** feature:
1. Adds **Institution Profile Header** to reports (fetched from `/api/auth/profile` with Bearer token authentication).
2. Introduces **chart visualization** (bar/pie charts) for placement statistics in the generated PDF.
3. Beautifies the **PDF layout** with styled headers, footers, and table design.
4. Includes **Excel export** improvements.
5. Handles fallback mock data when API fails, ensuring report generation works offline as well.
---
* `jspdf` → For PDF generation.
* `jspdf-autotable` → For generating formatted tables inside PDF.
* `chart.js` → For rendering charts.
* `chartjs-node-canvas` → For generating chart images on server-side (Node).
* `xlsx` → For Excel export.
* `file-saver` → For …
=> Implemented report generation

server/models/Student.js, server/routes/performance.js, server/seed.js, server/server.js
This PR implements the HR Performance Overview section for the HR Employee panel. It provides detailed performance metrics and visual insights for students eligible for placement.
solved issue #204
Overall Performance Metrics:
Total Placed Students
Total Interviews Conducted
Average Interview Attendance Percentage
Interactive Filters:
Select Year
Select Semester
Visual Charts:
Interview Attendance – Line chart
Pass vs Fail Ratio – Pie chart
Department-wise Performance – Line chart (Pass vs Fail comparison)
Data Fetching:
Integrated with backend API to fetch performance data by selected year and semester.
Displays loading and no-data states for better UX.
Verified data updates on changing year and semester.
Tested with different datasets to ensure charts render correctly.
Checked for edge …
=> Implement HR Performance Overview with metrics, charts, and filters

package-lock.json, package.json, src/App.jsx, src/data/challenges.js, src/pages/Student/Coding.jsx, src/pages/Student/CodingEditor.jsx
This PR introduces a new **Coding Practice** feature that allows users to browse common interview-style coding challenges, view challenge details in a modal, and open an interactive editor to attempt solutions. This is the first version, containing a few example problems to showcase the feature.
---
* **`src/pages/Coding.jsx`**
* Displays all coding challenges in a responsive grid layout.
* Uses `ChallengeCard` component for displaying individual challenge summaries.
* Opens a `Modal` when a challenge is clicked, showing:
* Title, difficulty, tags
* Problem description
* Starter code
* Actions:
* **Start Challenge** → navigates to the editor page for that challenge.
* **Show Solution** → navigates to editor page (solution handling to be implemented later).
* …
=> Added coding challenges fully working

server/controllers/studentController.js, server/routes/studentRoutes.js, server/server.js, src/App.jsx, src/components/SideBarStudent.jsx, src/components/StudentProgressCard.jsx, src/pages/Student/StudentProgressDashboard.jsx, src/pages/Student/StudentProgressDetail.jsx, vite.config.js
Description:
This pull request addresses issue [Insert Issue Number here, e.g., #125] by adding a new feature that allows students to track their interview progress.
Key Changes:
Frontend:
Adds a new Student Progress Tracker page accessible from the sidebar.
Displays a list of student cards with a progress bar, status, name, and email.
Implements search and filter functionality to easily find students.
Adds a new StudentProgressDetail.jsx page that shows a detailed view of a student's progress and feedback.
Uses a fetch call to retrieve data from the backend.
Backend:
Adds new routes in studentRoutes.js for fetching both a list of students (/api/students/progress) and a single student (/api/students/:id).
Updates studentController.js with mock data and controller functions to serve this …
=> Added student progress tracker dashboard Feature

server/controllers/settingsController.js, server/models/Settings.js, server/routes/settingsI.js, src/pages/Institution/Analytics.jsx, src/pages/Institution/StudentPerformance.jsx
Implemented complete Student Performance component with:
Dashboard Stats: Total students, completion rates, average scores
Student Table: Name, department, interview status, scores, results
Advanced Filters: Search, status, department, date filtering
Detail Modal: Complete performance breakdown with feedback
Export Feature: CSV download of filtered data
Responsive Design: Works on all devices
Testing
Page loads correctly
All filters work properly
Modal opens with detailed view
Export functionality works
Responsive on mobile/desktop
closes #198
=> Add Student Performance page

src/pages/Institution/Settings.jsx
Description:
Fixes the empty Institution Settings page by integrating API data and rendering configurable sections:
Institution profile
Department & course management
User/role permissions
Notification settings
Integration settings
closes #202
=> Settings page

src/components/InterviewLeft.jsx, src/components/InterviewRight.jsx, src/pages/Student/InterviewInterface.jsx
**Summary:**
Issue : #224 
This PR implements live transcription of user responses during mock interviews using the **Web Speech API**. Users can now answer questions either by typing or by speaking through their microphone, with spoken responses appearing in real time in the answer field for review before submission. This enhances realism and usability for the interview simulation.
---
* **State Management:**
* Added `transcript` and `setTranscript` in parent to maintain a single source of truth for the live transcription/answer field.
* Passed `transcript` and `setTranscript` to both `InterviewLeft` and `InterviewRight` to synchronize mic input and typing.
* **Handlers:**
* `handleStreamReady` → Sets camera/mic stream readiness state.
* `handleRecordingReady` → Captures the …
=> Add Real-Time Speech-to-Text Integration for Mock Interview

src/App.jsx, src/pages/ContactPage.jsx, src/pages/RoleSelectionPage.jsx
**This pull request introduces a new, dedicated contact page to the application. The page provides multiple ways for users to get in touch with our team**.
**Key Changes:**
New ContactPage.jsx Component: A new page has been created and styled with Tailwind CSS.
Google Form Integration: An embedded Google Form has been added to the page, allowing users to submit inquiries without a backend. This form will automatically send submissions to a designated Google Sheet.
"Meet the Team" Section: A section showcasing key team members has been included to add a personal touch and build trust with users.
FAQ Section: A list of frequently asked questions is now present to help users find immediate answers.
Updated Routing: The application's main routing file has been configured to properly render …
=> Add Contact Page with Google Form Integration

src/App.jsx
=> Fixed the issue in frontend rendering

src/components/FormInput.jsx, src/pages/register/CompanyForm.jsx
closes #244 
- Updated FormInput to support multiple focus colors (default: purple) and maintain consistent light/dark mode styling.
- Added smooth focus animation and removed unwanted browser outline for better UI/UX.
- Preserved password visibility toggle, required field indicators, and input styling.
- Updated CompanyForm to include Framer Motion animations for form and error alerts, enhancing interactive and responsive feel.
- Maintained theme consistency across light and dark modes for all components.
- Provides reusable, flexible input fields with dynamic focus colors.
- Enhances form experience with smooth animations and better visual feedback.
- Improves overall UI/UX and maintains accessibility standards.
I have checked the changes on my local machine and the pr is ready to merge …
=> Added animation  to comapny form  using framer motion and updated the forminput to support diffrent colour themes

src/index.css, src/pages/LandingPage.jsx
**Enhance Overall Homepage with Gradients, Theme-Based Colors, and Vibrant UI Effects**  
---
This PR revamps the **homepage UI** by introducing a more **modern, vibrant, and theme-aware design**.  
The update focuses on **gradients, hover interactions, spacing adjustments, and dark mode consistency**, making the homepage more visually engaging and user-friendly.  
closes #261
---
- Added **gradient backgrounds** for sections to improve visual flow.  
- Applied **theme-based color handling** (light & dark mode friendly).  
- Enhanced **hover effects** with smooth transitions and subtle scaling.  
- Improved **spacing and section separation** for better readability.  
- Refined **borders and shadows** for a polished, modern look.  
---
- Homepage looks **more vibrant and interactive**.  
- …
=> Enhance Overall Homepage with Gradients, Theme-Based Colors, and Vibrant UI Effects

src/components/Footer.jsx
**📌 Description**  
This PR improves the footer design by adding a **modern gradient background** and **subtle border accents** to align better with the overall theme.  
The changes enhance visual hierarchy, create smoother transitions between sections, and improve theme consistency across light and dark modes.  
closes #262
**🔧 Changes Made**  
- Added gradient background to footer for a modern aesthetic.  
- Introduced subtle border styling for smoother section separation.  
- Improved color consistency with the rest of the UI.  
- Ensured responsiveness and clean look in both light and dark themes.  
**✅ Expected Behavior**  
- Footer should now feel visually consistent with the site’s overall theme.  
- Borders should be subtle, not distracting, but still provide clear separation.  
- …
=> Enhance Footer with Gradient Background & Subtle Border Styling  

src/components/Footer.jsx
=> Implement dynamic year in footer.jsx

src/pages/Student/InterviewExperience.jsx
closes #275 
**Changes Made**
- Added InterviewExperience component to showcase real candidate stories.
- Implemented responsive card-based layout for company interview details.
- Integrated gradient backgrounds with smooth hover animations (hover:scale-105).
- Added dark theme support with dark: classes for seamless light/dark transitions.
- Designed hero section with gradient background and descriptive text.
- Added background decorations (blurred radial shapes & subtle grid pattern).
- Created call-to-action section encouraging users to share experiences.
- Used Lucide icons (Star, Briefcase) for a modern visual touch.
- Applied accessibility-friendly contrast and readable typography across themes.
-
**Purpose**
- Provide an engaging UI for displaying interview experiences.
- Encourage …
=> Added darktheme to interview experience page and redesigned the page

src/pages/Student/Aptitude.jsx
closes #277 
**Changes Made**
- Added Aptitude Page to showcase sample aptitude questions.
- Designed a modern, responsive layout with a clear structure:
- Header section: gradient background with bold title and short description.
- Questions section: interactive cards with hover effects, smooth animations, and clean typography.
- Footer CTA section: gradient background with a motivational call-to-action and action button.
- Implemented card-based UI for questions with styled options as clickable buttons.
- Added subtle hover animations (hover:-translate-y-1, hover:shadow-xl) for interactive feel.
- Integrated dark theme support across the page:
- Dark gradients for header & footer.
- Dark background for question cards (dark:bg-gray-800/70).
- Proper text contrast adjustments …
=> added dark theme support to aptitude page and designed the page

src/App.jsx, src/pages/LandingPage.jsx, src/pages/Resume.jsx
This PR upgrades the Resume Builder with a **more user-friendly, modern interface** while retaining all original features.
🔹 Key Enhancements:
* **Compact Form Layout** → Easier to fill without overwhelming the user
* **Visual Template Gallery** → 10–15 variations with different color schemes
* **Photo Upload Support** → Personalization option for resumes
* **Improved Preview Panel** → Scales perfectly across devices
* **Drag-and-drop, Inline Editing, and PDF Export** → All previous functionality maintained
---
* Provides a **smoother editing workflow** for users
* Makes **template selection faster and more visual**
* Improves **responsiveness and professional look** of the builder
* Increases overall **usability and engagement**
---
* Works seamlessly on desktop, tablet, and mobile
* …
=> Added a resume builder

src/pages/Student/ResumeBuilder.jsx
closes #287 
**📌 Summary**
- This PR introduces a UI/UX enhancement for the Resume Builder page.
- Added dark theme support across all form elements and page sections.
- Implemented auto-expanding textareas (Summary, Education, Experience) to improve readability and avoid scrollbars.
- Applied modern gradient backgrounds, rounded corners, and smooth transitions for a polished look.
**✨ Key Changes**
- Added dark:bg-* and dark:text-* Tailwind classes for all input fields, labels, and containers.
- Introduced a dynamic textarea resizing function (autoResize) that adjusts height based on user input.
- Replaced default scrollbars with smooth expansion behavior (resize-none + overflow-hidden).
- Improved contrast and readability in dark mode for inputs, labels, and buttons.
- Maintained …
=> Added dark theme support to the resume builderpage and improved ui

src/api/apiClient.js, src/layouts/DashboardLayout.jsx, src/pages/Student/ResumeATS.jsx, src/pages/register/CompanyForm.jsx
* Fixes #307 
The **Resume ATS Checker page** was previously disconnected from the global theme provider, resulting in inconsistent UI compared to the rest of the platform. Dark mode was not applied properly, leading to broken design, poor readability, and an unprofessional feel.
This PR integrates the Resume ATS Checker page into the **global theme context**, refactors styles, and ensures complete **light/dark mode support** across all components of this page. Now, the ATS Checker seamlessly adapts to theme switching, aligning with the rest of the application’s design system.
* Connected Resume ATS Checker page to the global `ThemeContext` (used across the platform).
* Ensured dynamic adaptation of colors, typography, and backgrounds based on the selected theme.
* Refactored component …
=> Added support for light and darkmode in resume ats checker page

src/pages/register/CompanyForm.jsx
=> Correction made in CompanyForm

src/pages/company/Applicants.jsx, src/pages/company/Insights.jsx
Fixes #322 
Changes made:
Implemented CompanyInsightsPage.jsx to replace the empty page.
Added dynamic UI components for company analytics and insights.
Displayed key data such as Interview & Placement Trends, performance stats etc.
Improved dashboard navigation with structured layout and styled visuals.
Outcome:
The Company Insights Page is now functional and provides meaningful analytics instead of showing a blank screen.
=> Implemented CompanyInsights page

src/pages/RoleSelectionPage.jsx
=> Added register button

src/pages/RoleSelectionPage.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
=> Added Footer to different pages

src/pages/RoleSelectionPage.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
Updated forms:
✅ StudentForm.jsx - Student registration
✅ CompanyForm.jsx - Company registration
✅ EmployeeForm.jsx - HR Professional registration
✅ InstitutionForm.jsx - Institution registration
=> Added confirm password to form 

src/pages/company/postJob.jsx
closes #336 
**Description**
- This PR introduces a new Job Posting Form component that allows employers to submit job details in a structured and user-friendly format. The form is designed to align with the existing ResumeBuilder UI for consistency, while ensuring accessibility and dark mode support.
**1-Basic Job Details**
- Input fields for Job Title, Company Name, and Location.
- Job type selection dropdown (Full-Time, Part-Time, Internship, Contract).
- Optional salary field with placeholder guidance for format.
**2-Job Information Section**
- Auto-resizing textarea for job description.
- Requirements input with comma-separated skills/qualifications.
- Benefits section for employers to list role perks.
**3-UI & Design Consistency**
- Gradient background with dark mode support.
- …
=> Add Job Posting Form with UI Consistency and Dark Mode Support

index.html, src/pages/ProfilePage.jsx, src/pages/Student/Dashboard.jsx, src/utils/theme.js
Previous:
- Theme implementation was not proper.
- There was a floating theme toggle button in ProfilePage and a different one in Dashboard.
- When the page reloads,components used to get inappropriate colors, breaking the theme.
Now:
- A single theme toggle button.
- Theme sync across components
- No issues during page reload or different route navigation
=> Fixed theme issues

package-lock.json, package.json, src/App.jsx, src/components/ResumeBuilder/EducationForm.jsx, src/components/ResumeBuilder/ExperienceForm.jsx, src/components/ResumeBuilder/PersonalInfoForm.jsx, src/components/ResumeBuilder/ProjectsForm.jsx, src/components/ResumeBuilder/ResumePreview.jsx, src/components/ResumeBuilder/SkillsForm.jsx, src/components/ResumeBuilder/index.js, src/pages/Student/ResumeBuilder.jsx, src/utils/pdfGenerator.js, src/utils/resumeValidation.js
fixes : #309 
This PR significantly improves the **Resume Builder** feature by restructuring the form, adding dynamic sections, implementing data persistence, and introducing a real-time resume preview. The builder is now a fully usable feature instead of a placeholder.
1. **Restructured Form Fields**
* Converted **Education** and **Work Experience** from plain textareas into **structured dynamic sections**.
* Each Education entry includes: Institution, Degree, Start Date, End Date, and Description.
* Each Work Experience entry includes: Company, Role, Start Date, End Date, and Description.
* Users can **add multiple Education and Experience records** dynamically.
2. **Skills Handling**
* Replaced comma-separated skills input with a **tag/chip-based input system**.
* Skills are now …
=> Refractored and implemented robust resume builder system

server/controllers/resumeController.js, server/models/Resume.js, server/models/User.js, server/routes/resume.js, server/server.js
fixes : #310 
This PR introduces the **backend layer for the Resume Builder feature**.
It defines the database schema, routes, controllers, and middleware integration required to handle resume creation, retrieval, updates, and deletion.
Frontend integration will be handled in the **next PR** — for now, the backend is fully ready and tested.
---
* New **`Resume` collection** to store user resumes separately from the User model.
* Supports multiple resumes per user (future-proofing).
* Fields include:
* `fullName`, `email`, `phone`, `summary`
* `skills` (array)
* `education` (array of institutions, degrees, timeline, descriptions)
* `workExperience` (companies, roles, dates, descriptions)
* `projects` (title, description, tech stack, link)
* Includes:
* Pre-save cleanup (removes empty …
=> Backend Implementation for Resume Builder

src/api/resumeApi.js, src/pages/Student/ResumeBuilder.jsx
This PR introduces the complete **integration of the Resume Builder frontend with the backend APIs**.
Previously, the resume builder frontend was static and only handled local states, but now it is **fully connected to the backend**, enabling real-time persistence of user data, fetching existing resumes, and ensuring smooth user experience across sessions.
---
1. **API Integration**
* Connected frontend with backend APIs for CRUD operations (Create, Read, Update, Delete) on resumes.
* Implemented secure API calls with proper request/response handling.
2. **Authentication Support**
* Only authenticated users can create, edit, or fetch resumes.
* Ensured token-based authentication in API requests.
3. **Data Persistence**
* User resumes are now stored in the database instead of being lost on …
=> Implemented the integration of frontend and backend of resume builder

src/components/CompanyCollaboration/CardGrid.jsx, src/components/CompanyCollaboration/SectionWrapper.jsx, src/pages/company/Collaboration.jsx
closes #338 
**Description**
This PR adds a component-based collaborative page with a clean and modern UI, built to be reusable and easy to maintain. The design is split into modular sections that focus on user experience and scalability.
**Component-Based Architecture**
- Reusable Components: HeroSection and CollaborationSection designed for flexibility and reuse.
- Separation of Concerns: Clear distinction between layout, content, and animations.
- Scalable Structure: Easy to extend with more sections or features in the future.
**Modern UI/UX Design**
- Hero Section: Eye-catching gradient background with bold typography and CTA button.
- Collaboration Section: Clean grid-based layout for features, benefits, and process.
- Consistency: Maintains a uniform design language across the page. …
=> Added collaboration section in Company section

src/pages/LandingPage.jsx
=> fixed go to dashboard button taking to register page issue

src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
Add a standard password policy in all forms for better password security maintaining all rules.
Added a checklist that turns green if a rule is obeyed
Fixes #375
=> add standard password policy checklist across forms

server/controllers/atsController.js, server/controllers/resumeScoreController.js, src/pages/Student/ResumeATS.jsx
This PR integrates the ATS scoring functionality from the backend into the frontend, making the scoring system visible, trackable, and engaging for users.
Previously, ATS scores were being stored in the backend, but the frontend had no way to:
* Send new scores to the backend.
* Retrieve past scores from the database.
* Display progress or improvements visually to the user.
This PR bridges that gap by implementing API integration and UI updates.
---
1. **Backend → Frontend Integration**
* On score generation, the frontend now automatically sends a POST request to save scores in the backend database.
* Implemented a new GET request to fetch score history (`/api/resume/score/:userId`) so users can see their past ATS scores.
2. **New UI Section: "Resume Progress"**
* Added a dedicated …
=> ATS Score Integration with Frontend

src/components/Footer.jsx
closes #392 📌 Description
This PR adds a newsletter subscription form to the footer to improve user engagement and provide users with timely updates.
Users can enter their email and subscribe.
Toast notifications are shown for success and error states.
Includes validation for proper email format.
Designed with minimal, clean UI for consistency with the existing footer.
✅ Changes Made
Added newsletter subscription form with input + Subscribe button.
Implemented email validation (basic regex check).
Added toast notifications:
✅ Success: "You have successfully subscribed!"
❌ Error: "Please enter a valid email." or "Subscription failed. Try again later."
Positioned toast at the bottom-right corner for better visibility.
Styled the input (white background) and button (purple/blue theme) for …
=> Add Newsletter Subscription with Toast Notifications

server/models/User.js
closes #402 
Removed the redundant fields for comapny and updated the enum to properly store role for institution,employee,admin,student,company etc . These changes were mandatory to have consistency and clarity .
=> Refactored schema and maitained consistency

package-lock.json, package.json, server/services/ats/atsScorer.js, src/components/Footer.jsx
The alignment issue in the **footer component** has been fixed.
Hi @MonishRaman,
While working on this issue, I encountered some problems with running the backend server. I identified a few bugs and fixed them as part of this PR. Since the work involved both frontend (footer alignment) and backend debugging, I’d appreciate it if this PR could be considered for a **Level 2** tag.
=> Fixed the alignment issue in footer component

src/components/Chatbot.jsx, src/components/Footer.jsx
Fixed the issue with chatbot component.
Now it is properly rendered without overlapping
=> fixed the ui breakage in chatbot component

ml_modules/answer_accuracy/FUZZY_MATCHING_README.md, ml_modules/answer_accuracy/keyword_checker.py, ml_modules/answer_accuracy/test_fuzzy_keyword_checker.py, ml_modules/requirements.txt
This PR #404 enhances the keyword checker by integrating fuzzy string matching using the rapidfuzz library. This allows the system to intelligently evaluate answers by accounting for typos, synonyms, or different phrasing.
Key Changes:
Fuzzy Matching Logic: Updated answer_accuracy/keyword_checker.py to use rapidfuzz for similarity-based keyword matching.
New Dependency: Added rapidfuzz to the ml_modules/requirements.txt file.
Testing & Docs:
Added a new test file, test_fuzzy_keyword_checker.py, to verify the new functionality.
Included FUZZY_MATCHING_README.md to document the new feature and its usage.
=> Enhance Keyword Checker with Fuzzy String Matching

src/pages/Student/Dashboard.jsx
Removed Mock Interview and Aptitude questions Link as it is already there in main sidebar
closes #407
=> Fixed the duplication of some sidebar links

server/controllers/jobController.js, server/routes/job.js, server/server.js
closes #409 
**Description**
This update introduces significant improvements to the Jobs module:
1-Added Update Controller – Implemented a dedicated controller to handle job updates, ensuring companies can modify their job postings securely and efficiently.
2-Router Setup for Jobs – Configured job routes with proper structure:
GET /api/jobs → Fetch jobs
POST /api/jobs → Create a new job (secured for company role)
POST /api/jobs/:id → Update an existing job (secured for company role)
3-Improved Existing Controller Logic – Refined and corrected the current jobs controller to handle validations, error handling, and consistent response formatting.
These changes enhance maintainability, add role-based access control, and ensure better scalability for future features.
**Request:  @MonishRaman …
=> Added Router and Update Functionality for jobs

package-lock.json, package.json, server/controllers/jobController.js, src/pages/Student/InterviewExperience.jsx
New form added in the Interview experience section.
Previously the Share your experience button was static 
Now it opens a model containing form
Request: Also @MonishRaman please increase the level for this pr has There was on issue in backend file which stopping to run successfully i have fixed also  I have added new feature so I expect it to get value.
=> feat: added form for taking interview experience response

src/pages/RoleSelectionPage.jsx
closes #425 
This PR adds a responsive navigation bar (navbar) to the landing page.
The navbar includes:
Logo on the left.
Navigation links: Sign up and Get started/Dashboard
Login / Signup button aligned to the right.
Sticky behavior: navbar remains visible while scrolling.
Responsive design: works seamlessly on desktop and mobile (hamburger menu for smaller screens).
Changes Made
Implemented a responsive navbar with proper alignment.
Added hamburger menu toggle for mobile view.
Ensured consistent styling across different screen sizes.
Improved overall navigation and brand visibility.
=> Add Responsive Navbar to Role selection Page

server/controllers/studentController.js, src/pages/RoleSelectionPage.jsx
closes #427 
Description
This PR updates the studentController.js to make the student APIs more robust and consistent.
Changes Made
Added parseInt for req.params.id in getStudentById to ensure numeric validation.
Added proper handling for invalid student IDs (400 Bad Request).
Improved error handling and logging across both controllers.
Cleaned up comments for better readability.
Ensured consistent data return for mockStudents and mockStudentDetails.
Why This is Needed
Prevents issues when non-numeric IDs are passed in the URL.
Provides clearer error responses (400 vs 404).
Improves code readability and maintainability.
Keeps API behavior predictable for frontend integration.
Checklist
GET /api/students returns all mock students.
GET /api/students/:id returns details for valid IDs. …
=> Improve Student Controller with Validation & Error Handling

server/yarn.lock, src/pages/company/CompanyProfile.jsx
closes #437 
**1. Dark Mode Support Added**
- Introduced Tailwind dark: variants for seamless theme switching.
- Updated container, inputs, textarea, and labels for proper visibility in dark mode.
- Ensured cancel button adapts to dark theme (dark:bg-gray-700).
**2. Background Fixes**
- Removed orange gradient in light mode and replaced with clean bg-white.
- Retained gradient background only for dark mode (dark:from-gray-900 …).
- Improved overall visual consistency with rest of the dashboard.
**3. Input & Form Enhancements**
- Inputs now adapt to both themes (bg-white dark:bg-gray-900).
- Borders and hover effects updated (dark:border-gray-700).
- Text readability improved with dark:text-gray-100.
**4. UI/UX Improvements**
- Smoother transitions between light and dark themes.
- Clear …
=> Added darkMode support and improved ui of company profile

server/controllers/authController.js
closes #446 
Description
The current authController.js had significant code duplication across the four registration functions:
registerStudent
registerInstitution
registerEmployee
registerCompany
Each function repeated logic for:
Checking if an email already exists (User.findOne({ email }))
Hashing the user’s password (bcrypt.hash(password, 10))
This violated the DRY principle, making the code harder to maintain and update consistently.
Changes Made
Extracted duplicated logic into helper functions:
checkEmailExists(email) → Ensures no duplicate email exists in the database.
hashPassword(password) → Handles password hashing with bcrypt.
Updated all registration functions to use these helpers.
Cleaned up implementation to focus on data mapping and model creation only.
=> Refactor: Remove Code Duplication in Authentication Controller

server/controllers/authController.js, server/controllers/settingsController.js
closes #448 
Overview
The settingsController.js contained heavy code duplication and inconsistent handling of settings creation and encryption, especially in updateNotifications and updateIntegrations.
This PR introduces helper functions and constants to centralize logic, improve maintainability, and enforce consistency.
Problems Fixed
🔁 Duplicate Code: Settings creation repeated in multiple functions
🔒 Inconsistent Encryption: Different approaches for sensitive data
⚙️ Hardcoded Defaults: Defaults scattered across functions
🌀 Mixed Concerns: Encryption, defaults, and updates intertwined
🛠️ Difficult Maintenance: Changes required updates in multiple places
What Changed
✨ Added getOrCreateSettings(userId) → centralizes settings retrieval/creation
✨ Added encryptSensitiveData(data, …
=> Refactor: Centralize Settings Creation & Encryption in settingsController.js

server/controllers/authController.js, server/controllers/emailController.js, server/controllers/settingsController.js, server/package-lock.json, server/package.json, server/yarn.lock
closes #447 
Overview
The emailController.js contained duplicated logic and mixed concerns across the sendFeedback and testEmailConfig functions.
This PR introduces helper functions to clean up the code, enforce validation, and improve error handling.
Problems Fixed
🔁 Code Duplication → Both functions created their own nodemailer.createTransport() instances
⚠️ Limited Validation → Only checked if a rating existed, not if it was in range
🌀Mixed Concerns → Transport creation, request handling, and formatting all in controllers
❌ Weak Error Handling → Generic error messages with no differentiation
What Changed
✨ Added createTransporter() → centralizes transporter creation
✨ Added sendEmail(mailOptions) → reusable email sending helper
✨ Added formatFeedbackContent(feedbackData) → separates …
=> Refactor: Centralize Email Handling & Validation in emailController.js

server/controllers/questionController.js, server/models/Question.js, server/routes/questions.js, server/server.js, server/yarn.lock
closes #441 
Dynamic Aptitude Questions Backend Integration
Summary
This PR introduces a scalable backend for managing aptitude questions, replacing the previous static frontend approach. The new system allows questions to be stored, retrieved, and answered dynamically via API endpoints.
Changes
Added Question model with fields: question, options, answer, explanation, topic.
Created controller for:
`GET /api/questions (with optional topic filtering)`
`POST /api/questions/answers (answer submission, returns correctness and explanation)`
Added Express route for questions API.
Integrated with MongoDB using existing connection setup.
Ensured validation and error handling for new endpoints.
Impact
Enables dynamic question management and future scalability.
Prepares the system for full-stack …
=> feat(server): add aptitude question api

server/controllers/questionsController.js, server/models/Question.js, server/routes/questions.js, server/services/ai/gemini.js, server/services/ai/geminiService.js
closes  #442 
This PR introduces **backend support for dynamically generating aptitude questions** using the **Gemini API**.
* Added a Gemini-powered question generation function in **`services/gemini.js`**.
* Created a new controller **`questionsController.js`** with a `POST /api/questions/generate` endpoint.
* Updated **`routes/questions.js`** to expose the new endpoint.
* Extended the **`Question` model** to include:
* `difficulty` → defines question difficulty level.
* `source` → tracks whether a question was Gemini-generated or manually added.
* Enables **scalable and interactive aptitude quizzes** by generating questions on demand.
* Provides seamless integration of AI-generated questions into the existing quiz system and database.
* Improves flexibility by allowing topic and …
=> feat(questions): add generate question endpoint

server/controllers/jobController.js, server/routes/job.js
closes #420 
**1. Delete Job API**
- Companies should be able to manage their job postings securely.
- Ownership Restriction: Only the company that originally created the job posting should be able to delete it.
- Admin Privileges: Admin users should also have the right to delete any job posting if needed.
- Authorization & Validation: API must validate the authenticated user’s role and ownership before allowing deletion. Unauthorized users should be restricted.
- Response Handling: On successful deletion, return a confirmation response. In case of errors (job not found, unauthorized access, etc.), return clear and meaningful error messages.
**2. Apply for Job (Applicants)**
- Candidates must be able to apply for jobs in a structured and secure way.
- Job Application: The system should …
=> Added delete Job and Apply Job endpoint

src/components/AptitudePreparation.jsx
* Replaced static JSON questions with **dynamic API calls** to backend.
* Fetches questions from `/api/questions?topic=...`.
* If no questions exist for the selected topic, the backend **auto-generates new ones via Gemini**.
* Submits answers through `/api/answers` and provides **instant feedback**.
* Added **loading, error, and empty states** for smoother user experience.
* Ensures **end-to-end flow** for aptitude quizzes is now fully production-ready.
* Makes quizzes **dynamic and scalable**, removing reliance on hardcoded questions.
* Provides a **seamless full-stack experience** with backend integration.
* Prepares the system for future features like difficulty levels, analytics, and progress tracking.
https://github.com/user-attachments/assets/9eed1331-c550-4974-ad24-c7fb467e88a4 …
=> feat: added backend integration in aptitute component

src/components/AptitudePreparation.jsx, src/components/Chatbot.jsx
closes #445 
* **Migrated Gemini API calls** from frontend → backend to ensure sensitive keys are never exposed.
* Implemented a secure backend endpoint at **`/api/chat`** to handle all chatbot interactions.
* Frontend now sends **user messages + full chat history** to backend for context-aware AI responses.
* Preserved:
* ✅ **Conversation continuity** (context maintained across turns)
* ✅ **Loading states** for smoother UX
* ✅ **Markdown rendering** for code blocks, formatting, etc.
* Added **robust error handling** to gracefully manage failed or delayed responses.
* 🚨 **Closes major security gap** → Gemini API key is fully hidden (not exposed in frontend or network tab).
* ⚡ Improves **scalability and maintainability** by centralizing AI logic in the backend.
* 🛠️ Backend-first …
=>  feat: Connect Chatbot frontend with backend API

server/controllers/resumeScoreController.js
closes #457 
📄 Description
This PR improves the Resume Score Controller by addressing performance bottlenecks, reducing redundant code, and enhancing maintainability while ensuring all existing functionality remains intact.
🚀 Changes Implemented
Parallelized queries
Replaced sequential DB queries with Promise.all() in analytics endpoints for faster execution.
Efficient user existence check
Replaced User.findById() with User.exists() to reduce overhead when verifying users.
Utility functions
Introduced reusable helpers for:
Error handling
ID validation
Sort field building
Sort field validation
Added validation logic to prevent invalid or potentially unsafe sort field inputs.
Error handling refactor
Consolidated duplicate error handling logic into shared utilities for consistency and …
=> Optimize Resume Score Controller for Performance & Maintainability

server/controllers/resumeController.js, server/controllers/resumeScoreController.js
closes #458 
📄 Description
This PR refactors the Resume Controller to improve performance, consistency, and maintainability, while preserving all existing functionality for user resume CRUD operations.
🚀 Changes Implemented
Efficient user verification
Replaced User.findById() with User.exists() to reduce unnecessary DB overhead.
Consistent error handling
Consolidated scattered error handling into reusable utility functions.
Fixed version increment
Corrected updateResume logic to properly increment resume version during updates.
Utility functions
Added common helpers for:
Error handling
Object ID validation
ID validation improvements
Enforced object ID validation on all relevant endpoints to prevent invalid queries.
=> Optimize Resume Controller for Performance & Reliability

server/controllers/atsController.js, server/controllers/resumeController.js, server/controllers/resumeScoreController.js
closes #459 
📄 Description
This PR enhances the ATS Controller by optimizing performance, improving error handling, and strengthening validation while ensuring all existing functionality for resume analysis and scoring remains intact.
🚀 Changes Implemented
Parallel analysis execution
Replaced sequential Gemini + multi-factor scoring with Promise.allSettled() for faster, resilient execution.
Non-blocking database operations
Refactored DB interactions to run asynchronously without blocking the response cycle.
Utility functions
Added reusable helpers for:
Error handling
Input validation
File cleanup
Comprehensive input validation
Implemented stricter validation to ensure safe and predictable API behavior.
File cleanup improvements
Refined cleanup process with proper error handling to avoid …
=> Optimize ATS Controller for Performance & Reliability

src/pages/Student/Dashboard.jsx
=> Improved responsive design

src/pages/Student/Dashboard.jsx
Closes: #491 
This pull request addresses the need for a functional notification system on the Student Dashboard. Previously, the notification bell icon was a static UI element with no interactivity. This PR brings it to life by implementing a dropdown panel that displays recent user notifications.
This change significantly improves user engagement by providing immediate access to important updates, such as new resume scores, upcoming interview schedules, and goal progress.
- New NotificationPanel Component: A reusable component was created to display the notification list. It is styled to match the application's dark and light themes.
- Interactive Bell Icon: The static Bell icon in the StudentDashboard header has been converted into a functional button.
- A red dot indicator is …
=> Feat(Dashboard): Implement Interactive Notification Panel

src/App.jsx, src/components/CompanySidebar.jsx, src/pages/company/MyCompanyJobs.jsx
closes #503 
This component displays all jobs posted by the currently logged-in company in a paginated card layout.
**Job Data Source:**
- Currently uses a temporary JSON array (sampleJobs) as mock data.
- Each job includes id, title, company, description, and profileImage.
- This allows the job cards to be rendered without relying on a backend API.
**Features:**
- Displays job cards in a grid layout (2 columns on medium screens).
- Shows company logo/name, job title, and job description.
- Includes an Update button for each job card.
- Supports pagination (default: 6 jobs per page).
Includes a Refresh button to reload jobs (currently just reuses the mock data).
**Next Steps:**
- Replace mock JSON (sampleJobs) with actual API data.
- Integrate backend filtering so only the logged-in …
=> Added a Page For CompanyPostedJobs

server/controllers/authController.js, src/pages/register/InstitutionForm.jsx
closes #497 
---
The institution registration flow was previously broken due to validation errors in the schema (`Institution` role not being recognized as a valid enum value). This PR resolves the issue and ensures that institutions can now register successfully.
Additionally, the registration logic has been enhanced with **robust debugging and error handling**, so any potential failures in the future can be easily identified and addressed.
---
* Updated schema to correctly include `Institution` as a valid enum value for the `role` field.
* Fixed validation errors in the institution registration controller.
* Improved error handling with clear messages and structured logs.
* Added detailed comments in the controller to explain the flow and interactions for future contributors.
* Ensured …
=> fix(auth): normalize institution role value

server/yarn.lock, src/pages/Institution/InstitutionDashboard.jsx
This PR integrates the Institution Dashboard with the backend API to display real user data instead of mock data. The dashboard now fetches and displays actual institution profile information from the authentication endpoint.
- ✅ Integrated API call to fetch institution profile data
- ✅ Replaced mock data with real data from `InstituteData` state
- ✅ Added proper error handling and loading states
- ✅ Enhanced welcome section to display real institution information
- ✅ Added fallback values for graceful loading experience
- **API Endpoint**: `GET /api/auth/profile`
- **Authentication**: Bearer token from localStorage
- **Data Fields Integrated**:
- Institution name
- Email address
- Website URL
- Contact person information
- 📧 Display institution email in welcome section
- 🌐 Added …
=>  Feature: Backend Integration for Institution Dashboard

src/pages/register/InstitutionForm.jsx
closes #510 
Description:
Fixes frozen input fields in Institution registration form by adding the missing handleFormDataChange function.
Changes Made:
Added handleFormDataChange function to manage form state updates
Function handles all input fields except password (which has its own handler)
Added error clearing when user starts typing
Type
Bug Fix - Critical form functionality
=> Institution Form Input Fields

server/yarn.lock, src/pages/Institution/StudentPerformance.jsx
This PR addresses responsiveness issues in the `StudentPerformance` component, ensuring it properly adapts to sidebar states and different screen sizes.
1. **Container Layout**
* Removed restrictive `max-w-7xl` container.
* Replaced with `w-full max-w-none` for full-width adaptation.
* Updated padding with responsive utilities (`p-4 sm:p-6`).
2. **Stats Cards Responsiveness**
* Grid adapts from 1 column (mobile) → 4 columns (xl screens).
* Responsive padding, icon sizing, and truncation added.
* `flex-shrink-0` applied to prevent distortion.
3. **Filter Section Improvements**
* Mobile-first stacked layout → horizontal on larger screens.
* Input and dropdowns adjusted with min-widths for readability.
* Export button adapts text visibility based on screen size.
4. **Table Responsiveness**
* …
=> Fix: Make StudentPerformance Component Fully Responsive with Sidebar State

.gitignore, server/models/CouponModel.js, server/models/PaymentModel.js, server/routes/Payment.js, server/yarn.lock
This PR introduces the missing **Payment** and **Coupon** Mongoose models which were previously absent from the codebase, causing the backend to fail when importing these models in `routes/Payment.js`.
* **Payment Model**:
* Handles transaction details such as transactionId, userId, amount, discounts, status, payment method, currency, and metadata.
* Includes schema validations, indexes for query optimization, and proper enum values for status & payment method.
* **Coupon Model**:
* Defines discount logic via percentage/fixed values, usage limits, applicable roles, validity periods, and activity status.
* Provides helper virtuals (like `isCurrentlyValid`) and methods (like `incrementUsage`).
* Includes indexes for performance improvements.
* Backend crash due to `ERR_MODULE_NOT_FOUND` for …
=> fix(backend): add required models

server/yarn.lock, src/App.jsx, src/pages/Institution/InstitutionProfile.jsx
closes #501 
This PR enhances the institution profile flow by ensuring all registration data is dynamically prefetched from the backend and properly mapped in the profile page. Users now see their institution details auto-populated, reducing redundancy and improving usability.
* **Fixed Field Mapping**
* Updated `institutionName` → `name` to align with backend response.
* **Dynamic Data Prefetching**
* Institution profile now automatically loads:
* Institution Name (read-only)
* Email (read-only)
* Website (editable)
* Contact Person (editable)
* Phone, Address, Established Year, Total Students, Accreditation, Description (all editable).
* **Improved Form Behavior**
* Registration fields (`name`, `email`) are now **read-only** to avoid accidental overwrites.
* Editable fields remain fully …
=> Fix: Prefetch Institution Profile Data & Improve Dynamic Profile Form

server/controllers/feedbackController.js
closes #523 
- Added `createTransporter()` helper to eliminate duplication.  
- Simplified improvements mapping with optional chaining.  
- Standardized return statements and error handling.  
- Cleaned up transporter reuse across both methods.  
No functional changes.  
Improved maintainability, consistency, and readability of feedback email handling.
=> Refactor feedbackController.js for cleaner structure and consistency

src/App.jsx, src/pages/company/EditJob.jsx, src/pages/company/MyCompanyJobs.jsx
closes #527
**1-Core Functionality**
- Prefill all fields (title, type, domain, location, status, salary, description).
- Requirements & responsibilities load as comma-separated editable text areas.
- Company name & website displayed read-only (no edit allowed).
**2-UI / UX**
- Responsive layout (mobile → desktop).
- Dark/light mode consistent with existing PostJob page.
- Action buttons: Save (mock), Delete (confirm), Cancel (back).
**3-Data Flow**
- Receives full job object via navigate state from MyCompanyJobs card.
- Fallback structure ready for future fetch by ID (if direct URL).
- Delete + update currently console.log payload (placeholder for API).
**4-Acceptance Criteria**
- Navigating via Update fills every editable field correctly.
- Company block cannot be modified (no …
=> Added a EditJob page for Company

src/App.jsx, src/components/CursorToggle.jsx, src/components/Header.jsx, src/context/CursorContext.jsx, src/layouts/CompanyDashboardLayout.jsx, src/layouts/DashboardLayout.jsx, src/layouts/EmployeeDashboardLayout.jsx, src/layouts/InstitutionDashboardLayout.jsx, src/pages/LandingPage.jsx
closes #516 
Added cursor toggle button in header for the entire website for users to let use their prefered cursor while the bubble cursor being the default
=> Toggle button for cursor added

src/App.jsx, src/components/CursorToggle.jsx, src/components/Header.jsx, src/context/CursorContext.jsx, src/layouts/CompanyDashboardLayout.jsx, src/layouts/DashboardLayout.jsx, src/layouts/EmployeeDashboardLayout.jsx, src/layouts/InstitutionDashboardLayout.jsx, src/pages/AuthPage.jsx, src/pages/LandingPage.jsx, src/pages/RoleSelectionPage.jsx
closes  #517 
For new users after clicking the signup link from Sign in form the app renders get started page without any indication where to register.
##Solution:
Added auto-scroll feature when when user clicks on signup renders register page and auto scrolls to register buttons.
=> Auto scroll to register buttons section after clicking signup for better user understanding

server/controllers/authController.js, src/pages/employee/PerformanceOverview.jsx, src/pages/employee/SkillDevelopmentTracker.jsx
Summary
Implementing comprehensive employee performance dashboard with interactive charts, multi-tab navigation, and data export functionality.
Key Features
- Multi-tab Interface: Overview, Achievements, and Insights sections
- 5 Chart Types: Line chart (performance trend), horizontal progress bars (skills), donut chart (completion rates), area chart (monthly activity), and metric cards
- Interactive Elements: Period selection (1M/3M/6M/1Y), CSV export, responsive design
- Performance Metrics: Overall score, task completion, project delivery, goals achievement with color-coded indicators
Technical Implementation
- Component: `PerformanceOverviewDashboard.jsx` using React hooks and Recharts
- Styling: Tailwind CSS with responsive design and smooth animations
- Data Structure: Mock data …
=> Performance Overview Dashboard

src/pages/employee/LearningResources.jsx
Implements comprehensive learning resource management and tracking system for employee professional development.
Features Added:
-  Resource Discovery: Advanced search, filtering by category/type, bookmark system
-  Learning Paths: Curated skill-based learning journeys with progress tracking
-  Progress Analytics: Learning hours tracking, completion stats, activity timeline
-  Smart Categorization: Technical, Soft Skills, Domain-specific resource organization
-  Responsive Design: Mobile-first approach with modern card-based UI
Technical Implementation:
React Hooks: useState for state management, dynamic filtering logic
Recharts Integration: Line charts for progress visualization over time
Interactive Components: Tab navigation, bookmark toggles, progress indicators
Tailwind Styling: …
=> Learning Resources Hub - Employee Learning Platform

src/pages/employee/CareerProgression.jsx
Summary
Implements interactive Career Progression module with career path exploration, milestone tracking, and achievement dashboard.
Features Added
Career Path Cards: Frontend, Full Stack, and Product Manager tracks with roadmaps
Milestone Tracking: Progress bars, task lists, and status indicators
Achievement Dashboard: Recent accomplishments showcase
Responsive Design: Mobile-friendly with smooth animations
Technical Details
React component with hooks and state management
Consistent with existing Placify design system
Responsive grid layouts using Tailwind CSS
Interactive elements with hover effects
Testing Checklist
Desktop and mobile responsive
Interactive elements functional
Smooth animations working
Progress tracking accurate
🔗 Related Issue
Closes #538
=>  Add Career Progression Feature

src/App.jsx, src/pages/company/MyCompanyJobs.jsx
1-Card UI parity with Student Jobs
Match Jobs.jsx card theme: colors, rounded corners, shadows, badges.
Display layout: title, company, salary, description (line-clamp), type/domain/status chips, meta (location/date).
Ensure responsive grid and dark mode classes consistent with Jobs.jsx.
2-Filters aligned with getCompanyJobs
Add filters: status, title, description, fromDate, toDate (client-side apply).
Reset to page 1 on any filter change; add Clear and Refresh actions.
Date range handling: toDate inclusive (set 23:59:59.999) for correct comparisons.
3-Data flow and navigation
Keep existing Update button behavior: navigate(/dashboard/company/jobs/:id/edit, { state: { job } }).
Use API data when available; fallback to dummyJobs on error or missing token.
Maintain PAGE_SIZE=6 with …
=> Improved CompanyJobs Page and added Filters

src/pages/ContactPage.jsx
closes #535 
Uses X icon instead of twitter icon
=> Refactor ContactPage: reorder imports and replace Twitter icon with SVG

src/components/FormInput.jsx, src/pages/register/CompanyForm.jsx, src/pages/register/EmployeeForm.jsx, src/pages/register/InstitutionForm.jsx, src/pages/register/StudentForm.jsx
closes #534
Added explicit `id` props to all `FormInput` components in `CompanyForm.jsx`, `EmployeeForm.jsx`, and `InstitutionForm.jsx`, ensuring each input and label are properly linked
=> Refactor form components to include unique IDs for inputs and improve password validation logic

server/models/CouponModel.js, server/models/PaymentModel.js, src/pages/company/EditJob.jsx
closes #547 
1-Secure Backend Integration
Verify PATCH /api/jobs/:id and DELETE /api/jobs/:id route order and role (company, admin).
Add single GET fetch only when page loaded directly (no duplicate calls if state provided).
Handle 401/403 distinctly (token missing vs unauthorized company).
2-Update & Delete Logic Hardening
Prevent update if no field changed (deep compare against original snapshot).
Normalize request payload (strip empty strings, trim arrays).
Graceful delete flow: confirm -> disable buttons -> navigate after success.
3-Toast Notification UX
Success: Job updated (2s), Job deleted (2s) before/while redirect.
Info: No changes detected (2s) skips network call.
Error: Surface server message or fallback string; avoid duplicate stacking.
4-API Call Reduction & Performance
Use …
=> Integrated backend to update and delete Job

server/controllers/interviewExperienceController.js, server/controllers/jobController.js, server/controllers/settingsController.js
Fixes #568 
- This PR optimizes the interviewExperienceController.js file by:
---
**Changes Made**
- Extracting validation logic into a reusable utility
- Adding a standard error handler for consistent responses
- Using Promise.all for parallel queries in pagination
- Improving code readability and consistency
---
**Checklist:**
-  Code refactored without changing functionality
-  Error handling standardized
-  Redundancy removed
-  All endpoints tested and working
=> Optimize interviewExperienceController.js for readability & performance

server/controllers/institutionController.js, server/controllers/interviewExperienceController.js, server/controllers/jobController.js, server/controllers/settingsController.js
Fixes #569 
- This PR optimizes the getInstitutionDashboard endpoint by:
---
**Changes made:**
- Adding a reusable error handler
- Using .lean() for better query performance
- Cleaning up array mappings with destructuring
- Returning consistent JSON responses
---
**Checklist:**
-  Functionality unchanged
- Performance improved using .lean()
-  Error handling standardized
-  Tested and verified responses
=> Optimize getInstitutionDashboard function

src/components/CompanySidebar.jsx
closes #576 
The current company sidebar component is functional but can be significantly improved in terms of user experience, code structure, accessibility, and features. This issue outlines a plan to refactor and enhance the sidebar for better performance and usability.
1. UI and UX Improvements
Refine Visual States: Improve the distinction between active, hover, and focus states for menu items to provide clearer visual feedback to the user.
Enhance Tooltip Behavior: Optimize the tooltips in the collapsed state with smoother animations and more consistent positioning to prevent layout shifts.
Standardize Iconography: Ensure all icons and text are perfectly aligned and use a consistent size and weight for a more polished and professional appearance.
2. Code Refactoring and Optimization …
=> Improved Company Side Bar Behaviour

package-lock.json, package.json, src/pages/company/EditJob.jsx
closes #580 
Improve Overall User Interface (UI):
Implement a modern layout with a gradient background and a blurred glass effect for the form container to enhance visual appeal.
Redesign input fields, select dropdowns, and text areas for better visibility and a consistent look across the form.
Update action buttons (Save, Delete, Cancel) with gradient colors and interactive hover animations for better user feedback.
Implement Themed Delete Confirmation:
Replace the native browser window.confirm() dialog with a more robust and visually appealing modal from the sweetalert2 library.
The confirmation alert's theme (background and text color) must automatically adapt to the application's current light or dark mode.
Customize the alert's text and icons to provide a clear warning to the user …
=> Improved The ui of editjobpage And added Alert

server/controllers/javaDryRunController.js, server/routes/javaDryRun.js
closes  #558 
This PR adds support for **Java code dry-run validation** in the backend using **Gemini AI**. The feature allows users to submit Java code and test cases, which are simulated securely via Gemini without requiring a Java runtime environment on the server.
* **Controller:** `javaDryRunController.js`
* Handles `POST /api/java-dry-run` requests.
* Builds prompts for Gemini AI, calls the API, and parses results.
* Compares actual vs expected outputs and returns structured responses.
* Includes robust error handling and inline documentation.
* **Route:** `javaDryRun.js`
* Exposes the new endpoint for Java dry-run.
* Connects the controller with the Express server.
* **Server Integration:**
* Registered the new route in `server.js` for seamless API access.
**Endpoint:** `POST …
=> feat: Implement Backend Dry-Run for Java Code

server/controllers/cDryRunController.js, server/routes/cDryRun.js, server/routes/dryrun.js, server/server.js
closes #559
This PR extends the backend to support **C and C++ code dry-run validation** using **Gemini AI**, following the same secure, scalable pattern as the existing Python and Java dry-run endpoints.
* **Controller:** `cDryRunController.js`
* Handles C/C++ code submissions with `language` (`c` or `cpp`) and test cases.
* Simulates execution via Gemini AI and compares outputs with expected results.
* Returns standardized, frontend-friendly responses.
* Includes detailed comments for maintainability and team collaboration.
* **Route:** `cDryRun.js`
* Exposes a new endpoint: `POST /api/c-dry-run`.
* Connects the controller with Express for API access.
* **Server Integration:**
* Registered the new C/C++ dry-run route in `server.js`.
* Ensured consistent ES module imports for Python …
=> feat: Implement Backend Dry-Run for C-Cpp

src/pages/AuthPage.jsx, src/pages/ContactPage.jsx, src/pages/company/EditJob.jsx
Currently, the password field allows users to submit a password that contains only a single character. This poses a security risk and does not meet standard password requirements.
closes #483
Added validation to ensure the password must be at least 6 characters long.
Display a custom error message if the password length is insufficient.
Updated form submission logic to prevent submission of invalid passwords.
Enhances password security and enforces minimum length requirements.
Improves user experience with clear feedback for invalid passwords.
=> Fix login form validation

server/controllers/authController.js, src/pages/register/CompanyForm.jsx
closes #594
Title: Improve Company Registration Error Handling and Field Mapping
Description:
Fixed the company registration form to send the correct email field (instead of hrEmail) to the backend, matching the Mongoose schema requirements.
Updated error handling in the registration form to display more informative messages:
Shows specific error titles for backend validation errors (e.g., "Missing Email", "Invalid Role", "Validation Error").
Displays "Backend not connected" if the backend is unreachable.
Provides descriptive server error messages for easier debugging.
Ensured all required fields are validated before submission.
Enhanced user feedback with clear toast notifications for both success and error states.
These changes improve the reliability and user experience of the company …
=> feat: Fix Company logic

src/pages/company/Employees.jsx
=> feat: adding sample ui in Employee Performance Page

src/pages/company/CompanyDashboard.jsx
closes #596
Now the company dashboard having real data taken at time of registration
=> Dynamic company data

README.md
Fixes Issue number #624 
Successfully fixed the project structure tree in README.md file thus making it easier for new contributors to navigate through the codebase and find relevant files easily. This reduces inconsistency and confusion.
=> Fixed the project structure tree in README.md

src/components/JobCard.jsx, src/pages/Student/Jobs.jsx
closes #636
Create a reusable JobCard component in React to display job listings consistently across the application. This component should be flexible and accept props for all dynamic data like job title, company, location, salary, type, domain, and status.
**Component Structure:**
Design the JobCard component with a top section for the company logo and job title.
Include a description section and a meta info section with tags for location, posted date, salary, type, domain, and status.
Props & Data Handling:
Accept props for job data (job) and helper functions (getImageUrl, formatDate).
Handle missing or fallback values for optional fields like logo, description, or salary.
**UI & Styling:**
Implement consistent tag styling for job metadata.
Include hover effects, …
=> Added reusable JobCard Component

src/pages/ProfilePage.jsx
closes #639 
Necessary Fields:
Include essential student information:
Full Name
Email
Phone
Date of Birth
Address
Education
University & Major
Skills & Technologies
Remove redundant fields or any placeholder/mock data that is not relevant to the student profile.
UI & Styling:
Apply a modern, responsive design using Tailwind CSS with support for light/dark themes.
Include hover effects, shadows, gradients, and smooth transitions for a polished user experience.
Save & Update Functionality:
Implement a “Save Changes” button that checks if any changes were made.
Display appropriate toast notifications for success, errors, or no changes.
Ensure image upload for profile picture is functional and previewable before saving.
=> Added required fields and removed redundant fields

package-lock.json, src/pages/company/Reports.jsx
closes #632 
---
* **Dashboard Layout**
* Header with title, actions, and description
* Responsive grid with statistics cards (Total, Completed, Processing, Downloads)
* **Filtering System**
* Search + filters for Type, Status, and Department
* Collapsible filter panel for cleaner UI
* **Reports Table**
* Columns: Name, Type, Status, Department, Date, Downloads
* Color-coded status badges + action dropdowns
* **Actions & Interactivity**
* "Generate Report" button with loading states
* Download / View / Share / Delete options
* Download count auto-updates
* **Recent Activity Feed**
* Shows latest report actions with user attribution & quick downloads
* **Design & UX Enhancements**
* Framer Motion animations, dark mode, responsive layout
* Empty/loading states, hover effects, dropdown …
=> feat: adding reports page in company dashboard

src/index.css, src/pages/employee/SkillDevelopmentTracker.jsx
closes #648 
Key Features Added:
Interactive Modal Component - A beautifully designed modal that opens when clicking the "Add Skill" button
Skill Name (required, with duplicate validation)
Category selection (Technical, Soft Skills, Domain)
Current Level slider (0-100%)
Target Level slider (0-100%)
Priority selection (Low, Medium, High)
Smart Validation:
Required field validation for skill name
Duplicate skill name detection
Range validation for skill levels
Target level must be higher than current level
Real-time error display
Dynamic UI Updates:
New skills immediately appear in the skills grid
Statistics automatically update (total skills, averages, etc.)
Charts and analytics reflect new data instantly
Skills are filterable and searchable immediately
Professional UX:
- Live preview of …
=> feat: made Add Skill Button working

src/pages/employee/EmployeeDashboard.jsx
closes #654 
- Removed static employeeData.
- Added API call with apiClient.get('/dashboard') (leverages existing auth interceptor).
- Introduced loading, error, and profile state.
- Derived role-specific fields (job title, department, work location).
- Added avatar initials generation.
- Displayed a subtle banner if additionalData.sample is present (indicates sparse data).
- Kept performance/goal metrics as clearly labeled placeholders.
- Added graceful fallbacks (e.g., '—' for missing values).
- Wrapped existing UI with dynamic data while preserving styling and structure.
1. Log in as an employee and visit /dashboard/employee.
2. Ensure:
3. Loading indicator shows briefly.
4. Dashboard renders your name or fallback.
5. Department/job title populated if present.
6. Sample banner appears …
=> feat: integrated with backend api of dashboard data

src/pages/employee/CompanyFeedback.jsx
closes #646
- A responsive table showing employee name, feedback, star rating, and date.
- Search and date filter functionality.
- A form to add new feedback (with star rating).
- Static sample data (no backend).
- Styling consistent with the dashboard and responsive for desktop/mobile.
=> feat: added company feedback page

src/components/EmployeeSidebar.jsx
Now the sidebar is more structured as discussed in the issue
closes  #645
=> feat: redesigned-emp-sidebar

src/pages/employee/JobSwitchInsights.jsx
closes #660
Job Switch Insights Page Implementation
Implemented the **Job Switch Insights** page, providing interactive data visualizations, market insights, and actionable recommendations. The page aligns with the existing dashboard design system and is fully responsive.
---
* **Overview Cards:** Market Demand (78%), Salary Growth (+34%), Optimal Switch Time (18 months), Industry Growth (+12.5%).
* **Charts (Recharts):**
* Salary Progression Bar Chart
* Industry Trends Line Chart
* Skills Demand Radar Chart
* **Job Opportunities:** Cards and table with filters (All, High Growth, High Salary, Culture Fit).
* **Market Insights:** Strategic insights, recent industry moves, and recommendations.
* **Action Cards:** Skill development, networking, and portfolio improvement.
---
* **Responsive …
=> feat: added job insights page

src/pages/employee/EmployeeDashboard.jsx, src/pages/employee/quickActionsConfig.js
closes #664
This PR converts the previously static **Quick Actions** section on the Employee Dashboard into a set of fully functional, navigable shortcuts. Each action now routes to its corresponding feature page and is defined via a centralized configuration for easier maintenance and scalability.
---
* Added **`quickActionsConfig.js`** defining all Quick Actions (icon, label, description, color, route).
* Refactored **`QuickActionCard`** into an accessible, keyboard-focusable button with hover, active, and focus-visible states.
* Introduced subtle motion effects (icon scaling, arrow shift).
* Replaced hardcoded JSX with `.map()` rendering from config.
* Integrated navigation using `useNavigate` from `react-router-dom`.
* Added inline documentation for easy future extensions.
* Preserved …
=> feat: made quick actions working
